version: "3.8"

services:
  # --- Production Service ---
  app-prod:
    profiles:
      - prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: batch_tracker_app_prod
    env_file:
      - .env
    environment:
      - CONF_ENV=prod
    volumes:
      # Mount a volume for persistent logs
      - app_logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - batch_tracker_network

  # --- MCP Service ---
  app-mcp:
    profiles:
      - mcp
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: batch_tracker_app_mcp
    env_file:
      - .env
    environment:
      - CONF_ENV=mcp
      - PYTHONPATH=/app
    volumes:
      # Mount local source code for live-reloading untill live reloading is needed for the development with MCP
      - ./app:/app/app
      - ./docs:/app/docs
      - ./tests:/app/tests
      - app_logs:/app/logs
    ports:
      - "8002:8000"
    networks:
      - batch_tracker_network

  # --- Development Service ---
  app-dev:
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: batch_tracker_app_dev
    env_file:
      - .env
    environment:
      - CONF_ENV=dev
      - PYTHONPATH=/app
    volumes:
      # Mount local source code for live-reloading
      - ./app:/app/app
      - ./docs:/app/docs
      - ./tests:/app/tests
      - app_logs:/app/logs
    ports:
      - "8001:8000" # Use a different host port to avoid conflicts
    networks:
      - batch_tracker_network

# Define named volumes for persistent data
volumes:
  app_logs:
    driver: local

# Define a custom network for the services
networks:
  batch_tracker_network:
    driver: bridge
